/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/parallel/": {
    /** Search Endpoint Parallel */
    post: operations["search_endpoint_parallel_parallel__post"]
  }
  "/primary/": {
    /** Search Endpoint Primary */
    post: operations["search_endpoint_primary_primary__post"]
  }
  "/secondary/": {
    /** Search Endpoint Secondary */
    post: operations["search_endpoint_secondary_secondary__post"]
  }
  "/summary/": {
    /** Summary Endpoint */
    post: operations["summary_endpoint_summary__post"]
  }
  "/explanation/": {
    /** Summary Endpoint No Stream */
    post: operations["summary_endpoint_no_stream_explanation__post"]
  }
  "/explanation-parallel/": {
    /** Summary Endpoint Parallel */
    post: operations["summary_endpoint_parallel_explanation_parallel__post"]
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** Body_search_endpoint_parallel_parallel__post */
    Body_search_endpoint_parallel_parallel__post: {
      /** Search Input */
      search_input: string
      input_encoding: components["schemas"]["InputEncoding"]
      search_type: components["schemas"]["SearchType"]
      filter_source_language: components["schemas"]["FilterLanguage"]
      source_limits: components["schemas"]["Limits"]
      filter_target_language: components["schemas"]["FilterLanguage"]
    }
    /** Body_search_endpoint_primary_primary__post */
    Body_search_endpoint_primary_primary__post: {
      /** Search Input */
      search_input: string
      input_encoding: components["schemas"]["InputEncoding"]
      search_type: components["schemas"]["SearchType"]
      filter_language: components["schemas"]["FilterLanguage"]
      limits: components["schemas"]["Limits"]
    }
    /** Body_search_endpoint_secondary_secondary__post */
    Body_search_endpoint_secondary_secondary__post: {
      /** Search Input */
      search_input: string
      input_encoding: components["schemas"]["InputEncoding"]
      search_type: components["schemas"]["SearchType"]
      filter_secondary: components["schemas"]["LimitsSecondary"]
      postprocess_model: components["schemas"]["PostProcessModel"]
    }
    /** Body_summary_endpoint_no_stream_explanation__post */
    Body_summary_endpoint_no_stream_explanation__post: {
      /** Query */
      query: string
      /**
       * Locale
       * @default en
       */
      locale?: string
      /** Summary */
      summary: string
    }
    /** Body_summary_endpoint_parallel_explanation_parallel__post */
    Body_summary_endpoint_parallel_explanation_parallel__post: {
      /** Query */
      query: string
      /** Src Text */
      src_text: string
      /** Tgt Text */
      tgt_text: string
      /** Src Translation */
      src_translation: string
      /** Tgt Translation */
      tgt_translation: string
      /**
       * Locale
       * @default en
       */
      locale?: string
    }
    /** Body_summary_endpoint_summary__post */
    Body_summary_endpoint_summary__post: {
      /** Query */
      query: string
      /** Summary */
      summary: string
      /**
       * Locale
       * @default en
       */
      locale?: string
    }
    /**
     * FilterLanguage
     * @description For primary and parallel data, we can filter by these languages.
     * @enum {string}
     */
    FilterLanguage: "tib" | "skt" | "chn" | "pli" | "all"
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * InputEncoding
     * @enum {string}
     */
    InputEncoding: "auto" | "tibetan" | "wylie" | "dev" | "iast" | "hk"
    /**
     * Limits
     * @description Limits for Search in primary sources. This is identical to the filter model of the xnexus endpoints.
     */
    Limits: {
      /**
       * Category Include
       * @default []
       */
      category_include?: unknown[]
      /**
       * File Include
       * @default []
       */
      file_include?: unknown[]
    }
    /**
     * LimitsSecondary
     * @description Limits for Search in secondary sources
     * @enum {string}
     */
    LimitsSecondary: ""
    /**
     * ParallelDataSearchResponse
     * @description List of individual search results for the parallel search.
     */
    ParallelDataSearchResponse: {
      /** Results */
      results: components["schemas"]["ParallelDataSearchResult"][]
    }
    /**
     * ParallelDataSearchResult
     * @description A single result from the parallel data search.
     */
    ParallelDataSearchResult: {
      /** Query */
      query: string
      /** Src Lang */
      src_lang: string
      /** Src Segmentnr */
      src_segmentnr: string
      /** Src Title */
      src_title: string
      /** Src Link */
      src_link: string
      src_text: components["schemas"]["TextSegment"]
      /** Tgt Lang */
      tgt_lang: string
      /** Tgt Segmentnr */
      tgt_segmentnr: string
      /** Tgt Title */
      tgt_title: string
      tgt_text: components["schemas"]["TextSegment"]
      /** Tgt Link */
      tgt_link: string
    }
    /**
     * PostProcessModel
     * @description If we do full RAG, we might want to postprocess the results with any of these models.
     * @enum {string}
     */
    PostProcessModel: "llama3" | "gpt-3.5" | "gpt-4" | "claude" | "none"
    /** PrimarySearchResponse */
    PrimarySearchResponse: {
      /** Results */
      results: components["schemas"]["PrimarySearchResult"][]
    }
    /** PrimarySearchResult */
    PrimarySearchResult: {
      /** Query */
      query: string
      /** Lang */
      lang: string
      /** Segmentnr */
      segmentnr: string
      /** Title */
      title: string
      /** Summary */
      summary: string
      /** Text */
      text: string
      /** Src Link */
      src_link: string
    }
    /**
     * SearchType
     * @description The type of search to be performed, regular here means a standard elastic search that is more or less precise, while semantic uses a semantic model with english as pivot language.
     * @enum {string}
     */
    SearchType: "regular" | "semantic"
    /** SecondarySearchResponse */
    SecondarySearchResponse: {
      /** Results */
      results: components["schemas"]["SecondarySearchResult"][]
    }
    /** SecondarySearchResult */
    SecondarySearchResult: {
      /** Title */
      title: string
      /** Author */
      author: string
      /** Year */
      year: string
      /** Page Link */
      page_link: string
      /** Summary */
      summary: string
      /** Text */
      text: string
    }
    /** SummaryRespone */
    SummaryRespone: {
      /** Summary */
      summary: string
      /**
       * Relevance
       * @enum {string}
       */
      relevance: "low" | "medium" | "high"
    }
    /**
     * TextSegment
     * @description We return text-Before and text_after as well to give context to the search results.
     */
    TextSegment: {
      /** Text Before */
      text_before: string
      /** Text Main */
      text_main: string
      /** Text After */
      text_after: string
      /** Translation */
      translation: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Search Endpoint Parallel */
  search_endpoint_parallel_parallel__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_search_endpoint_parallel_parallel__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ParallelDataSearchResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Search Endpoint Primary */
  search_endpoint_primary_primary__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_search_endpoint_primary_primary__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PrimarySearchResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Search Endpoint Secondary */
  search_endpoint_secondary_secondary__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_search_endpoint_secondary_secondary__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SecondarySearchResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Summary Endpoint */
  summary_endpoint_summary__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_summary_endpoint_summary__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Summary Endpoint No Stream */
  summary_endpoint_no_stream_explanation__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_summary_endpoint_no_stream_explanation__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SummaryRespone"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Summary Endpoint Parallel */
  summary_endpoint_parallel_explanation_parallel__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_summary_endpoint_parallel_explanation_parallel__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SummaryRespone"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
