/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/translation-fgs/": {
    /** Translation */
    post: operations["translation_translation_fgs__post"]
  }
  "/translation-no-stream/": {
    /** Translation No Stream */
    post: operations["translation_no_stream_translation_no_stream__post"]
  }
  "/translation-exp/": {
    /** Translation */
    post: operations["translation_translation_exp__post"]
  }
  "/translation/": {
    /** Translation */
    post: operations["translation_translation__post"]
  }
  "/tagging/": {
    /** Tagging */
    post: operations["tagging_tagging__post"]
  }
  "/available-models/": {
    /** Get Available Models */
    get: operations["get_available_models_available_models__get"]
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** AvailableModelsResponse */
    AvailableModelsResponse: {
      /** Models */
      models: components["schemas"]["TranslationModel"][]
    }
    /** Body_tagging_tagging__post */
    Body_tagging_tagging__post: {
      /** Input Sentence */
      input_sentence: string
      mode: components["schemas"]["GrammarModes"]
      input_encoding: components["schemas"]["InputEncoding"]
      /** Human Readable Tags */
      human_readable_tags: boolean
    }
    /** Body_translation_no_stream_translation_no_stream__post */
    Body_translation_no_stream_translation_no_stream__post: {
      /** Input Sentence */
      input_sentence: string
      input_encoding: components["schemas"]["InputEncoding"]
      target_lang: components["schemas"]["TargetLanguage"]
    }
    /** Body_translation_translation__post */
    Body_translation_translation__post: {
      /** Input Sentence */
      input_sentence: string
      input_encoding: components["schemas"]["InputEncoding"]
      /** Do Grammar Explanation */
      do_grammar_explanation: boolean
      target_lang: components["schemas"]["TargetLanguageExperimental"]
      model: components["schemas"]["TranslationModel"]
    }
    /** Body_translation_translation_exp__post */
    Body_translation_translation_exp__post: {
      /** Input Sentence */
      input_sentence: string
      input_encoding: components["schemas"]["InputEncoding"]
      /** Do Grammar Explanation */
      do_grammar_explanation: boolean
      target_lang: components["schemas"]["TargetLanguageExperimental"]
      model: components["schemas"]["TranslationModel"]
    }
    /** Body_translation_translation_fgs__post */
    Body_translation_translation_fgs__post: {
      /** Input Sentence */
      input_sentence: string
      input_encoding: components["schemas"]["InputEncoding"]
      target_lang: components["schemas"]["TargetLanguage"]
    }
    /** ErrorResponseModel */
    ErrorResponseModel: {
      /** Detail */
      detail: string
    }
    /**
     * GrammarModes
     * @enum {string}
     */
    GrammarModes:
      | "lemma"
      | "lemma-morphosyntax"
      | "unsandhied-lemma-morphosyntax"
      | "unsandhied"
      | "unsandhied-morphosyntax"
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * InputEncoding
     * @enum {string}
     */
    InputEncoding: "auto" | "tibetan" | "wylie" | "dev" | "iast" | "hk"
    /** Lemma */
    Lemma: {
      /** Lemma */
      lemma: string
      /** Unsandhied */
      unsandhied: string
      /** Tag */
      tag: string
      /** Meanings */
      meanings: string[]
    }
    /** Sentence */
    Sentence: {
      /** Sentence */
      sentence: string
      /** Grammatical Analysis */
      grammatical_analysis: components["schemas"]["Lemma"][]
    }
    /** TaggerResponseModel */
    TaggerResponseModel: components["schemas"]["Sentence"][]
    /**
     * TargetLanguage
     * @enum {string}
     */
    TargetLanguage:
      | "english"
      | "tibetan"
      | "sanskrit"
      | "sanskrit-dev"
      | "buddhist-chinese"
      | "korean"
      | "japanese"
      | "german"
      | "french"
      | "italian"
    /**
     * TargetLanguageExperimental
     * @enum {string}
     */
    TargetLanguageExperimental:
      | "english"
      | "english-explained"
      | "tibetan"
      | "sanskrit"
      | "sanskrit-dev"
      | "buddhist-chinese"
      | "korean"
      | "german"
      | "russian"
      | "french"
      | "italian"
      | "spanish"
      | "portuguese"
      | "dutch"
      | "hindi"
      | "japanese"
      | "pali"
      | "sanskrit-knn"
      | "modern-chinese"
    /**
     * TranslationModel
     * @enum {string}
     */
    TranslationModel:
      | "NO"
      | ""
      | "default"
      | "madlad"
      | "madlad2"
      | "llama3"
      | "llama3-fgs"
      | "gemma2"
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Translation */
  translation_translation_fgs__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_translation_fgs__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Translation No Stream */
  translation_no_stream_translation_no_stream__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_no_stream_translation_no_stream__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Translation */
  translation_translation_exp__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_translation_exp__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Translation */
  translation_translation__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_translation__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Tagging */
  tagging_tagging__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_tagging_tagging__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json":
            | components["schemas"]["TaggerResponseModel"]
            | components["schemas"]["ErrorResponseModel"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Get Available Models */
  get_available_models_available_models__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AvailableModelsResponse"]
        }
      }
    }
  }
}
