/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/translation/": {
    /** Translation */
    post: operations["translation_translation__post"]
  }
  "/search/": {
    /** Search Endpoint */
    post: operations["search_endpoint_search__post"]
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** Body_translation_translation__post */
    Body_translation_translation__post: {
      /** Input Sentence */
      input_sentence: string
      input_encoding: components["schemas"]["InputEncoding"]
      /** Level Of Explanation */
      level_of_explanation: number
      target_lang: components["schemas"]["TargetLanguage"]
      model: components["schemas"]["ModelName"]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * InputEncoding
     * @enum {string}
     */
    InputEncoding: "auto" | "dev" | "wylie" | "itrans" | "velthuis" | "hk"
    /**
     * ModelName
     * @enum {string}
     */
    ModelName: "NO" | "ANALYZE" | "GPT4TRANSLATE"
    /** SearchInput */
    SearchInput: {
      /** Search Input */
      search_input: string
    }
    /**
     * TargetLanguage
     * @enum {string}
     */
    TargetLanguage:
      | "english"
      | "sanskrit"
      | "tibetan"
      | "chinese"
      | "japanese"
      | "korean"
      | "pali"
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Translation */
  translation_translation__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_translation__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Search Endpoint */
  search_endpoint_search__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
