/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/translation/": {
    /** Translation */
    post: operations["translation_translation__post"]
  }
  "/search/": {
    /** Search Endpoint */
    post: operations["search_endpoint_search__post"]
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** Body_translation_translation__post */
    Body_translation_translation__post: {
      /** Input Sentence */
      input_sentence: string
      /** Input Encoding */
      input_encoding: string
      /** Level Of Explanation */
      level_of_explanation: number
      /** Target Lang */
      target_lang: string
      /** Model */
      model: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** SearchInput */
    SearchInput: {
      /** Search Input */
      search_input: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Translation */
  translation_translation__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_translation_translation__post"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  /** Search Endpoint */
  search_endpoint_search__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
