version: "3.7"

services:

  frontend:
    build:
      context: .
    container_name: "dmnext"
    restart: always
    ports:
    - "3333:3000"

  nginx:
    build:
      context: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"