version: "3.7"

services:

  dm-public:
    build:
      context: .
      args:
        BUILD_SCRIPT: build:dm
    container_name: "dm-public"
    restart: ${RESTART_POLICY}
    ports:
      - "3333:3000"

  dm-lab:
    build:
      context: .
      args:
        BUILD_SCRIPT: build:lab
    container_name: "dm-lab"
    restart: ${RESTART_POLICY}
    ports:
      - "3334:3000"

  kp:
    build:
      context: .
      args:
        BUILD_SCRIPT: build:kp
    container_name: "kp"
    restart: ${RESTART_POLICY}
    ports:
      - "3335:3000"

  nginx:
    build:
      context: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"
    depends_on:
      - dm-public
      - dm-lab
      - kp

