version: "3.7"

services:

  frontend:
    build:
      context: .
    container_name: "dmnext"
    restart: always
    ports:
    - "3333:3000"

#     networks:
#       - buddhanexus_default

# networks:
#   buddhanexus_default:
#     external: true