version: "3.7"

services:

  frontend:
    build:
      context: .
      args:
        BUILD_SCRIPT: ${BUILD_SCRIPT:-build:dm}
    container_name: "dmnext"
    restart: always
    ports:
      - "3333:3000"

  nginx:
    build:
      context: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"
    environment:
      # Default to root if not specified
      - BASE_PATH=${BASE_PATH:-''}  