version: "3.7"

services:

  # Pseudo-code placeholder for env setup.
  # frontend-dm-production:
  #   build:
  #     context: .
  #     args:
  #       BUILD_SCRIPT: build:dm-production
  #   container_name: "dmnext"
  #   restart: always
  #   ports:
  #     - "3333:3000"
  # frontend-dm-staging:
  #   build:
  #     context: .
  #     args:
  #       BUILD_SCRIPT: build:dm-staging
  #   container_name: "dmnext"
  #   restart: always
  #   ports:
  #     - "3333:3000"

  frontend:
    build:
      context: .
    container_name: "dmnext"
    restart: always
    ports:
    - "3333:3000"

  nginx:
    build:
      context: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"