services:

  pub:
    build:
      context: .
      args:
        BUILD_VARIANT: pub
    container_name: "pub"
    restart: ${RESTART_POLICY}
    ports:
      - "3333:3000"
    env_file:
      - .env.local

  lab:
    build:
      context: .
      args:
        BUILD_VARIANT: lab
    container_name: "lab"
    restart: ${RESTART_POLICY}
    ports:
      - "3334:3000"
    env_file:
      - .env.local

  rnd:
    build:
      context: .
      args:
        BUILD_VARIANT: rnd
    container_name: "rnd"
    restart: ${RESTART_POLICY}
    ports:
      - "3335:3000"
    env_file:
      - .env.local

  kumarajiva:
    build:
      context: .
      args:
        BUILD_VARIANT: kumarajiva
    container_name: "kumarajiva"
    restart: ${RESTART_POLICY}
    ports:
      - "3336:3000"
    env_file:
      - .env.local

  nginx:
    build:
      context: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"
    depends_on:
      - pub
      - lab
      - rnd
      - kumarajiva

