name: Build Development (rnd)
on:
  push:
    branches:
      - ai-provider
  workflow_dispatch:
jobs:
  build-and-test:
    strategy:
      matrix:
        variant: [rnd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: actions-env
      - uses: actions/setup-node@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: timestamp
        run: echo "NOW=$(date +'%Y-%m-%d-%H%m')" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DM_DH_USER }}
          password: ${{ secrets.DM_DH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: BUILD_VARIANT=${{ matrix.variant }}
          push: true
          tags: "${{ vars.DM_DH_USER }}/${{ vars.DM_DH_REPO }}:${{ matrix.variant }}-${{ steps.timestamp.outputs.NOW }},${{ vars.DM_DH_USER }}/${{ vars.DM_DH_REPO }}:${{ matrix.variant }}-latest"
