name: Build pub
on:
  push:
    branches:
      - pub
  workflow_dispatch:
jobs:
  build-and-test:
    strategy:
      matrix:
        variant: [pub]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: actions-env
      - uses: actions/setup-node@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: timestamp
        run: echo "NOW=$(date +'%Y-%m-%d-%H%M')" >> "$GITHUB_OUTPUT"

      - name: Get short SHA
        id: short_sha
        run: echo "SHA=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Set Sentry release version
        run: echo "SENTRY_RELEASE=${{ matrix.variant }}-${{ steps.short_sha.outputs.SHA }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DM_DH_USER }}
          password: ${{ secrets.DM_DH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BUILD_VARIANT=${{ matrix.variant }}
            SENTRY_RELEASE=${{ env.SENTRY_RELEASE }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
          push: true
          tags: "${{ vars.DM_DH_USER }}/${{ vars.DM_DH_REPO }}:${{ matrix.variant }}-${{ steps.timestamp.outputs.NOW }}-${{ steps.short_sha.outputs.SHA }},${{ vars.DM_DH_USER }}/${{ vars.DM_DH_REPO }}:${{ matrix.variant }}-latest"

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ matrix.variant }}
          version: ${{ env.SENTRY_RELEASE }}
          finalize: true
          # No sourcemaps here - they're uploaded by the webpack plugin
