name: Deploy
on:
  workflow_dispatch:
  pull_request:
    branches: [test-deploy]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # - name: Install project dependencies
      #   run: yarn install --frozen-lockfile

      # - name: Typechecking
      #   run: yarn test:ts

      # - name: Lint
      #   run: yarn lint

      # - name: Build
      #   run: yarn build

      # - name: Install Playwright Browsers
      #   run: yarn playwright install --with-deps

      # - name: Playwright tests
      #   run: yarn playwright test
      #   env:
      #     CI: 'true'

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 7
          
      - name: Get current date
        id: timestamp
        run: echo "NOW=$(date +'%Y-%m-%d-%H%m')" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.VA_DOCKERHUB_USERNAME }}
          password: ${{ secrets.VA_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "angirov/dmtest:dev-${{ steps.timestamp.outputs.NOW }},angirov/dmtest:latest"
