name: Validate and Release
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released PRs

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && '0' || '1' }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version to stable
        run: yarn set version stable

      - name: Install project dependencies
        run: yarn install --immutable

      - name: Yarn Audit
        run: yarn audit --level high
        continue-on-error: true

      - name: Typechecking
        run: yarn test:ts

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Playwright tests
        run: yarn playwright test
        env:
          CI: "true"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
