name: Release
on:
  push:
    branches: ["main"]

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released PRs

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for semantic-release

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version to stable
        run: yarn set version stable

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn" # Enable built-in yarn caching

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
