name: Test-env
on:
  workflow_dispatch:
    inputs:
      flavour:
        type: choice
        description: flavour
        options: 
          - lab
          - dm
          - kp
      stage:
        type: choice
        description: stage
        options: 
          - production
          - staging
  # pull_request:
  #   branches: [dev]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test-env
      - uses: actions/setup-node@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: timestamp
        run: echo "NOW=$(date +'%Y-%m-%d-%H%m')" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.VA_DOCKERHUB_USERNAME }}
          password: ${{ secrets.VA_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: DMENV=${{ github.event.inputs.flavour }}-${{ github.event.inputs.stage }}
          push: true
          tags: "${{ secrets.VA_DOCKERHUB_USERNAME }}/dmtest:${{ github.event.inputs.flavour }}-${{ steps.timestamp.outputs.NOW }},angirov/dmtest:latest"
