name: Validate release PR
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn" # Enable built-in yarn caching

      - name: Clear Yarn cache (cache bust)
        run: yarn cache clean --all
        continue-on-error: true

      - name: Clear TypeScript cache
        run: rm -rf .next node_modules/.cache tsconfig.tsbuildinfo
        continue-on-error: true

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Yarn Audit
        run: yarn npm audit
        continue-on-error: true

      - name: Typechecking
        run: yarn test:ts

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

    #   TODO: Uncomment this when we have Playwright tests
    #   - name: Install Playwright Browsers
    #     run: yarn playwright install --with-deps

    #   - name: Playwright tests
    #     run: yarn playwright test
    #     env:
    #       CI: "true"

    #   - uses: actions/upload-artifact@v4
    #     if: always()
    #     with:
    #       name: playwright-report
    #       path: playwright-report/
    #       retention-days: 7
